# Generated by Django 2.2.3 on 2020-04-29 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='modified_teim',
            new_name='modified_time',
        ),
    ]
